name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Package Build
      run: dotnet pack --configuration Release
    - name: Package Push to Github packages
      run: dotnet nuget push "bin/Release/*.nupkg" --source "https://nuget.pkg.github.com/circleboom/index.json" --api-key ${{secrets.NUGET_PRIVATE_FEED_PASSWORD}}
    
